"""add_subscription_levels

Revision ID: 1239a0133b29
Revises: 29bb77e45f98
Create Date: 2026-02-27 11:59:36.617184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1239a0133b29'
down_revision: Union[str, None] = '29bb77e45f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sub_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sub_end_date')
    op.drop_column('users', 'sub_level')
    # ### end Alembic commands ###
